In [2]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np

## Assignment

The goal of this project is to understand this traffic better, in particular the volume and distribution of events, and to develop ideas how to increase the links' clickrates. With that in mind, please analyze the data using the Python libraries Pandas and SciPy where indicated, providing answers to the presented questions:

<li>[Pandas] How many total pageview events did the links in the provided dataset receive in the full period, how many per day? </li>
<li>[Pandas] What about the other recorded events?</li>
<li>[Pandas] Which countries did the pageviews come from?</li>
<li>[Pandas] What was the overall click rate (clicks/pageviews)?</li>
<li>[Pandas] How does the clickrate distribute across different links?</li>
<li>[Pandas & SciPy] Is there any correlation between clicks and previews on a link? Is it significant? How large is the effect? Make sure to at least test for potential linear as well as categorical (think binary) relationships between both variables.</li>

#### Step 1: Getting information

In [3]:
raw = pd.read_csv('/Users/dungnguyen/Desktop/WORKSPACE/DS/StrataScratch/Website_Traffic_Analysis/datasets/traffic.csv')
raw.head()

,event,date,country,city,artist,album,track,isrc,linkid
0,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
1,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
2,click,2021-08-21,India,Ludhiana,Reyanna Maria,So Pretty,So Pretty,USUM72100871,23199824-9cf5-4b98-942a-34965c3b0cc2
3,click,2021-08-21,France,Unknown,"Simone & Simaria, Sebastian Yatra",No Llores Más,No Llores Más,BRUM72003904,35573248-4e49-47c7-af80-08a960fa74cd
4,click,2021-08-21,Maldives,Malé,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8

In [4]:
raw.describe()

,event,date,country,city,artist,album,track,isrc,linkid
count,226278,226278,226267,226267,226241,226273,226273,219157,226278
unique,3,7,211,11993,2419,3254,3562,709,3839
top,pageview,2021-08-19,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
freq,142015,35361,47334,22791,40841,40841,40841,40841,40841

In [6]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226278 entries, 0 to 226277
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   event    226278 non-null  object
 1   date     226278 non-null  object
 2   country  226267 non-null  object
 3   city     226267 non-null  object
 4   artist   226241 non-null  object
 5   album    226273 non-null  object
 6   track    226273 non-null  object
 7   isrc     219157 non-null  object
 8   linkid   226278 non-null  object
dtypes: object(9)
memory usage: 15.5+ MB

In [7]:
# convert date datatype from <object> to <date> type
raw["date"] = pd.to_datetime(raw["date"])
raw

,event,date,country,city,artist,album,track,isrc,linkid
0,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
1,click,2021-08-21,Saudi Arabia,Jeddah,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
2,click,2021-08-21,India,Ludhiana,Reyanna Maria,So Pretty,So Pretty,USUM72100871,23199824-9cf5-4b98-942a-34965c3b0cc2
3,click,2021-08-21,France,Unknown,"Simone & Simaria, Sebastian Yatra",No Llores Más,No Llores Más,BRUM72003904,35573248-4e49-47c7-af80-08a960fa74cd
4,click,2021-08-21,Maldives,Malé,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8
...,...,...,...,...,...,...,...,...,...
226273,pageview,2021-08-24,Kuwait,Kuwait City,Sean Paul,The Trinity,Temperature,USAT20505520,04ba6b17-1055-4f0e-a75e-3cdb0d0d4106
226274,pageview,2021-08-24,India,Chennai,Miscél,when you left,when you left,QM42K1907890,2fc15e8b-83aa-40ee-9f9d-5d96c6d4356c
226275,pageview,2021-08-24,India,Jaipur,"Trippie Redd, Lil Uzi Vert",Holy Smokes (feat. Lil Uzi Vert),Holy Smokes,QZJ842001118,eedc8702-6bd2-499a-972f-260c35f72e0f
226276,pageview,2021-08-24,France,Unknown,Young Thug,Tick Tock,Tick Tock,USAT22104514,e0a76dc3-7ccd-405f-8ee8-a2c55c0e0ed2
226277,pageview,2021-08-24,Iraq,Duhok,Tesher,Jalebi Baby,Jalebi Baby,QZNWQ2070741,2d896d31-97b6-4869-967b-1c5fb9cd4bb8

In [43]:
# [Pandas] How many total pageview events did the links in the provided dataset receive in the full period, how many per day?
def q1_function():
    df_1 = raw.copy()
    # return df_1.groupby( by = ["date","event"])["event"].count()
    print("How many total pageview events did the links in the provided dataset receive in the full period, how many per day?")
    pageview_cnt = df_1.loc[df_1["event"] == "pageview"]["event"].count()
    print("pageview count: ", pageview_cnt)
    date_cnt = df_1["date"].nunique()
    print("total date count: ", date_cnt)

    print( "pageview events per day: ", int(pageview_cnt / date_cnt) )
q1_function()

How many total pageview events did the links in the provided dataset receive in the full period, how many per day?
pageview count:  142015
total date count:  7
pageview events per day:  20287

20287.85714285714

In [60]:
#[Pandas] What about the other recorded events?
def q2_function():
    df = raw.copy()
    df_event = pd.DataFrame(df[["event"]].groupby(by = ["event"])["event"].count()).rename( columns= {"event" : "events_cnt"}).reset_index()
    df_event["date_cnt"] = pd.DataFrame(df[["event","date"]].groupby(by = "event")["date"].nunique()).reset_index()[["date"]]
    df_event["event_per_date"] = round(df_event["events_cnt"] / df_event["date_cnt"])


    return df_event
q2_function()

      event  events_cnt  date_cnt  event_per_date
0     click       55732         7          7962.0
1  pageview      142015         7         20288.0
2   preview       28531         7          4076.0